export const USER_REQUEST = 'USER_REQUEST';
export const USER_FAILURE = 'USER_FAILURE';
export const USER_SUCCESS = "USER_SUCCESS";
export const LOG_OUT = "LOG_OUT";
export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_FAILURE = "GET_USER_FAILURE";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const UPDATE_USER = "UPDATE_USER";
export const TAG_SKILL_REQUEST = 'TAG_SKILL_REQUEST';
export const TAG_SKILL_FAILURE = 'TAG_SKILL_FAILURE';
export const TAG_SKILL_SUCCESS = 'TAG_SKILL_SUCCESS';
export const ADD_TAG_SKILL_SUCCESS = 'ADD_TAG_SKILL_SUCCESS';
export const DELETE_TAG_SKILL_SUCCESS = 'DELETE_TAG_SKILL_SUCCESS';
export const  GET_LIST_USER_SUCCESS = 'GET_LIST_USER_SUCCESS';
export const GET_LIST_STUDENT_SUCCESS = 'GET_LIST_STUDENT_SUCCESS';
export const UPDATE_TAG_SKILL_SUCCESS = ' UPDATE_TAG_SKILL_SUCCESS';
export const SET_STATUS_STUDENT_SUCCESS = 'SET_STATUS_STUDENT_SUCCESS';
export const SET_STATUS_TEACHER_SUCCESS = 'SET_STATUS_TEACHER_SUCCESS';
export const GET_USER_DETAIL_SUCCESS = 'GET_USER_DETAIL_SUCCESS';
//Constants CONTRACT
export const FETCH_CONTRACT_REQUEST = 'FETCH_CONTRACT_REQUEST';
export const FETCH_CONTRACT_SUCCESS = 'FETCH_CONTRACT_SUCCESS';
export const FETCH_CONTRACT_FAILURE = 'FETCH_CONTRACT_FAILURE';
export const UPDATE_CONTRACT_SUCCESS = 'UPDATE_CONTRACT_SUCCESS';
//Static Income
export const FETCH_INCOME_FAILURE = 'FETCH_INCOME_FAILURE';
export const FETCH_INCOME_SUCCESS = 'FETCH_INCOME_SUCCESS';
export const FETCH_INCOME_REQUEST = 'FETCH_INCOME_REQUEST';
//Complaint
export const FETCH_COMPLAINT_SUCCESS = 'FETCH_COMPLAINT_SUCCESS';
export const UPDATE_COMPLAINT_SUCCESS = 'UPDATE_COMPLAINT_SUCCESS';
export const FETCH_MESSAGE_SUCCESS = 'FETCH_MESSAGE_SUCCESS';